# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del c칩digo
        uses: actions/checkout@v4

      - name: Configurar Python 3.10
        uses: actions/setup-python@v4  # Cambiado a la versi칩n m치s reciente
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint con flake8
        run: |
          # Detener la construcci칩n si hay errores de sintaxis o nombres indefinidos
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero trata todos los errores como advertencias. El editor de GitHub tiene 127 caracteres de ancho
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
